**My First Python Demo Notebook – A Simple Tutorial**

_Description is coming soon..._

<details>

<summary>Table of content</summary>

# Notebook content

- [I: Some basic commands to get ready](#some-basic-commands-to-get-ready)
- [II: Feeding my dataframe with new data](#title)
- [III: Energy consumption and power profile](#title)
- [IV: Some references to go further](#title)
- I : Visual Studio code
- II : JupyterNotebook
- III : Python
- IV : Variable type
- V : NumPy and Pandas
- VI : Data from csv
- VII : Manipulation of dataframe
- VIII : Plot of dataframe
- IX : Pandapower

</details>

---

<details>

<summary>TODO</summary>

## Ideas for this tutorial

- [ ] Trying to get more data on energy consumption.
- [ ] Obtain primary or secondary energy consumption per capita.
- [ ] Do the same exercise with electricity consumption per capita.
- [ ] Compare growth with energy efficiency.
- [ ] Add a comparison between pandas and numpy [pd/np](https://www.geeksforgeeks.org/difference-between-pandas-vs-numpy/)
- [ ] Understand Dictionnary of dataframe exemple [Dictionnary of dataframe](#Dictionnary-of-dataframe) at this link [dict_of_df](https://www.educative.io/answers/how-to-create-a-dictionary-of-data-frames-in-python)
- [ ] Modifying the Dictionnary of dataframe to correspond pandapower exercise
- [ ] Details on variable type need to be completed

</details>

---

# VS code



File -> Activate Autosave

Launch via terminal, nice to open project.

Some features : 
- Dark mode or other
- Friendly git command
  - Git [nomenclature](https://www.conventionalcommits.org/en/v1.0.0/)
- Github Copilot
- Extension

# JupyterNotebook

All the [basics](00_welcome_to_jupyter.ipynb) about JupyterNotebook.
- What is it ?
- Step by step execution
- How memory work
- Variable explorer
- Export


Here you have the [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for markdown.

Few usefull shortcut :
- `y` and `m` to toggle between markdown and python cells.
- `Ctrl+Enter` to run cells
- `Shift+Enter` to run and advance in next cells

And text higligh : 
 - ``---`` - Line througth the page
 - `>` - Text box
 - \`Text\` - Quoting code like ``this``
 - And triple for multiple line \`\`\` ``code`` \`\`\`

# Some basics to get ready


At the first, we are not informatician, the hygiene is important for your code : commenting, good variable name,...

But if that works... ;)

Here a complete guide about hygiene coding tips : [hygiene_tips](https://testdriven.io/blog/clean-code-python/), I recommend you to read the _PEP 8_ part.

For solving a problem, you have many solution and that the same with Python, so we will give you one solution (sometimes more) and that can be the best solution, or not. 

So be free as a bird and make your own experience. :bird:

### Python



Python is an object oriented programming language and this mean that almost everything is an object with own properties and methods.

And we create object with the constructure (like blueprint) called Class.

And each object can have function inside, thats called method.

## Help once the package has been imported


Python works with package, this is all the code already developped that we can use, we don't want (and can't) recode anything every times.

Package exit to do lots of thinks : statistical analysis, data visualization, etc.

In this tuto we'll import the following packages :
- *numpy* and *pandas* for data analysis and manipulation
- *plotly* for data visualization
- (*os* is used to change working directories, but you don't need it)

In [1]:
import os
import numpy as np
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots

For needed information on a function tape : _?function_name_

In [ ]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

## Basics Data Structures and Sequences : Variable type

The information is stocked in variable, the information can take multiple forms, numeric, string, etc., the next table resume the data type and how to construct it.
|                  | Data Type  | Example                                              |
|------------------|------------|------------------------------------------------------|
| _Text Type_      | str        | `"Hello World"`                                      |
| _Numeric Types_  | int        | 50                                                   |
|                  | float      | 50.5                                                 |
|                  | complex    | 10j                                                  |
| _Sequence Types_ | list       | `["resistance", "admittance", "impedance"]`          |
|                  | tuple      | `("resistance", "admittance","impedance")`           |
|                  | range      | `range(8)`                                           |
| _Mapping Type_   | dict       | `{"Element": "Generator", "Power" : 100}`            |
| _Boolean Type_   | bool       | True, False                                          |

On this [link](https://wesmckinney.com/book/python-builtin#tut_data_structures), you have more information about the datastructure.

<details>
<summary>Details on variable type</summary>

- **Integers** are whole numbers, negative and positive.
- **Floats** are real numbers or numbers with a decimal point.
- **Strings** are sequences of characters.
- **Booleans** are True or False  (1 or 0).
- **Tuples** are ordered, immutable collections of values.
- **dictionaries** is unordered collection of data in a key: value pair form
- **Lists** are ordered, mutable collections of values.


</details>


The program auto define the variable type when we create it.  It's possible to manually specify it (for changing size p.ex.).

In [ ]:
# List exemple
list_test = [9, 1, 2, 3, 4, "z", "x", "y", "x"]
print("Classe of list_Test:\n", type(list_test))
print("list_Test contains:\n", list_test)

Classe of list_Test:
 <class 'list'>
list_Test contains:
 [9, 1, 2, 3, 4, 'z', 'x', 'y', 'x']


In a sequence, the elements can be accessed with `[]`.

Like C or most of the common programming language, Python index begin at 0, unlike Matlab, who start at 1.

In [ ]:
print("Element 3 in list_Test =", list_test[2])

Element 3 in list_Test = 2


List and Tuple are similar, but Tuple is immutable.

In [ ]:
list_exemple = ["foo", [1, 2], True]
tup_exemple = ("foo", [1, 2], True)
print("Type of tup :", type(tup_exemple))
print("Type of list :", type(list_exemple))

Type of tup : <class 'tuple'>
Type of list : <class 'list'>


In [ ]:
# tup[2] = False

To access value inside, the procedure is the same :

In [ ]:
list_exemple[1]

[1, 2]

To access sub-element :

In [ ]:
list_exemple[1][1]

2

### Complex number
A complex value can be expressed in polar coordinates or rectangular coordinates :

![Impedance](plot/impedance.png)

In [ ]:
# Rectangular
R_real = 10
X_imag = 5
Z = R_real + 1j * X_imag
# Polar
Tension_Module = 10
Phase_Angle = 45
U = Tension_Module * np.exp(1j * Phase_Angle)

But Python express complex number in rectangular coordinates :

In [ ]:
print("Impedance = ", Z)
print("Tension = ", U)

Impedance =  (10+5j)
Tension =  (5.253219888177298+8.509035245341185j)


## Manipulating NumPy array and Pandas dataframe

For manipulating data, we can use two packages, they are similar but not exactly the same, here a small explanation of the differences [pd/np](https://www.geeksforgeeks.org/difference-between-pandas-vs-numpy/#:~:text=Difference%20between%20Pandas%20and%20Numpy)

Pandas is based on NumPy and is usefull to manipulate data-structures (Tabular data) : numeric data (or not) and time series

Numpy is the fundamental library of Python, it provides high-performance multidimensional arrays and tools to work with them, usefull to matrix and vector calculation.

### Numpy
_array_ is like _list_ but faster, from NumPy library (continuous place in memory unlike _list_)

Use _list_, _tuple_ or any _array-like_ to construct NumPy array

In [ ]:
# Create narray with list and multiple dimension
array_list = np.array(
    [
        [[1, 2, 3], [4, 5, 6]],
        [[7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18]],
    ]
)
print(array_list.ndim)
print(array_list)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
array_list[2][0]

array([13, 14, 15])

In [6]:
# Time interval
years = np.arange(1900, 2021, 10)
print(years)

# Population data for Switzerland
pop = np.array(
    [
        3297641,
        3708897,
        3870407,
        4042131,
        4233223,
        4692642,
        5327776,
        6180925,
        6319848,
        6713167,
        7184003,
        7825751,
        8640582,
    ]
)


## (just for information)
# Convert each number to a string with thousand separators
formatted_pop = np.array(list(map(lambda x: f"{x:,}", pop)))

# Print the formatted population array verticaly
print("\n".join(formatted_pop))

[1900 1910 1920 1930 1940 1950 1960 1970 1980 1990 2000 2010 2020]
3,297,641
3,708,897
3,870,407
4,042,131
4,233,223
4,692,642
5,327,776
6,180,925
6,319,848
6,713,167
7,184,003
7,825,751
8,640,582


Now I would like to visualize the population evolution that will change over time:

In [7]:
# Create a DataFrame
df = pd.DataFrame({"Year": years, "Population": pop})

# Create a line plot
fig = px.line(
    df,
    x="Year",
    y="Population",
    title="Population Evolution of Switzerland",
    labels={"Population": "Population", "Year": "Year"},
)

# To format and save figures
fig.update_layout(
    margin=dict(l=60, r=60, t=60, b=60),
    coloraxis_showscale=False,  # Remove the color bar
    width=800,  # Width of the figure in pixels
    height=500,  # Height of the figure in pixels
)

# Show the plot
fig.show()

### Dataframe
A dataframe (df) contain a dictionary, it's a list of values linked to keys. The size of the df is define by the number of values (row) and keys (columns).

When a df is created, an index is autocreate if we don't specify one, it contain a list from 0 to n-1 (n = number of values).

In [2]:
exemple_of_dictionnary = {
    "key 1": [1, 2, 3, 4, 5],
    "key 2": [1, 2, 3, 4, 5],
    "key 3": 3,
    "key 4": ["a", "b", "c", "D", "E"],
}

my_dico = {
    "taille de population": 10,
    "moyenne age": 42,
    "pays": "Suisse",
}

pd_exemple = pd.DataFrame(exemple_of_dictionnary)
##Add a column
pd_exemple["year"] = [
    2010,
    2011,
    2012,
    2013,
    2014,
]

##Change a column to index
pd_exemple_2 = pd_exemple.set_index("year")

In [3]:
print("Base index :\n", pd_exemple)
print("Custom index :\n", pd_exemple_2)

Base index :
    key 1  key 2  key 3 key 4  year
0      1      1      3     a  2010
1      2      2      3     b  2011
2      3      3      3     c  2012
3      4      4      3     D  2013
4      5      5      3     E  2014
Custom index :
       key 1  key 2  key 3 key 4
year                           
2010      1      1      3     a
2011      2      2      3     b
2012      3      3      3     c
2013      4      4      3     D
2014      5      5      3     E


> **Note** In a df, each column is a series. A series is a one-dimensional array containing data of any type.

In [4]:
type(pd_exemple["year"])

pandas.core.series.Series

#### Access to dataframe values 

##### Access to the column value(s) :



The two methodes :

Dot Notation (`.column_name`)
- **Syntax**: `dataframe.column_name`
- **Usage**: This is a shorthand for accessing columns.
- **Limitations**:
  - The column name must be a valid Python identifier (e.g., no spaces, special characters, or starting with a number).
  - It can lead to ambiguity if the column name conflicts with DataFrame methods or attributes.
Bracket Notation (`["column_name"]`)
- **Syntax**: `dataframe["column_name"]`
- **Usage**: This is the more flexible and recommended way to access columns.
- **Advantages**:
  - Can handle column names with spaces, special characters, or names that are not valid Python identifiers.
  - Avoids conflicts with DataFrame methods or attributes.

<details>
<summary>Name column problem</summary>

The method to access a column use the name of the column, and sometimes the name contain space. 

In this case, the first method can't work, this [link](https://saturncloud.io/blog/how-to-access-pandas-columns-with-spaces-in-column-names/) explain the problem.

</details>

In [ ]:
print("Access to column:\n", pd_exemple["key 1"])
print("Access to column:\n", pd_exemple_2["key 1"])
print("Access to column other methode:\n", pd_exemple.year)
print("Access to multiple columns:\n", pd_exemple[["key 1", "key 3"]])

Access to column:
 0    1
1    2
2    3
3    4
4    5
Name: key 1, dtype: int64
Access to column:
 year
2010    1
2011    2
2012    3
2013    4
2014    5
Name: key 1, dtype: int64
Access to column other methode:
 0    2010
1    2011
2    2012
3    2013
4    2014
Name: year, dtype: int64
Access to multiple columns:
    key 1  key 3
0      1      3
1      2      3
2      3      3
3      4      3
4      5      3


##### Access the row value(s) :

The `.loc` and `.iloc` methods in Pandas are used for accessing and manipulating data in DataFrames, but they differ in how they select data.

- ``.loc``: Use when you want to select data by labels.
- `.iloc`: Use when you want to select data by integer positions.

To use `loc`, we create a series of boolean value that we passe to the function, this series is construct by the equality operator `==`, we check, p.ex. a column with a value.

And for `iloc`, we just pass an integer who correspond to the index position. 

More selection possibility for [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) and [iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html).

In [ ]:
print("Index access to row:\n", pd_exemple.loc[0])
print("Index access to row:\n", pd_exemple_2.loc[2010])
print("Access to specific element\n", pd_exemple_2.loc[pd_exemple_2["key 4"] == "D"])
print("Index access to multiple row:\n", pd_exemple_2.loc[2010:2012])

Index access to row:
 key 1       1
key 2       1
key 3       3
key 4       a
year     2010
Name: 0, dtype: object
Index access to row:
 key 1    1
key 2    1
key 3    3
key 4    a
Name: 2010, dtype: object
Access to specific element
       key 1  key 2  key 3 key 4
year                           
2013      4      4      3     D
Index access to multiple row:
       key 1  key 2  key 3 key 4
year                           
2010      1      1      3     a
2011      2      2      3     b
2012      3      3      3     c


## Use external data files like csv

Now I would like to use the same value but from a csv file, and only save the value from Switzerland, not for all the countries. Also charging the electricity values.

In [ ]:
# Go to the good workplace folder
# os.chdir("..")
os.chdir(os.getcwd().replace("/tutorials", ""))
print("We are here", os.getcwd())
os.chdir("tutorials")
print("We are here", os.getcwd())

We are here p:\School\HES\ResoHT\workspace\rhtlab\workspace


FileNotFoundError: [WinError 2] The system cannot find the file specified: 'tutorials'

In [8]:
# Load data from our world in data

df_population = pd.read_csv("data/population-and-demography.csv", sep=",")

df_electricity_generation = pd.read_csv("data/electricity-generation.csv", sep=",")
# Take only swiss data = row selection
df_swiss_population = df_population.loc[df_population["Entity"] == "Switzerland"]
df_swiss_electricity_generation = df_electricity_generation.loc[
    df_electricity_generation["Entity"] == "Switzerland"
]

The first thing when we create a dataframe from csv file or other sources, is to check the data :

In [ ]:
df_swiss_population.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 16428 to 16501
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype 
---  ------                                                 --------------  ----- 
 0   Entity                                                 74 non-null     object
 1   Code                                                   74 non-null     object
 2   Year                                                   74 non-null     int64 
 3   Population - Sex: all - Age: all - Variant: estimates  74 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 2.9+ KB


In [ ]:
df_swiss_population

Entity Code  Year  \
16428  Switzerland  CHE  1950   
16429  Switzerland  CHE  1951   
16430  Switzerland  CHE  1952   
16431  Switzerland  CHE  1953   
16432  Switzerland  CHE  1954   
...            ...  ...   ...   
16497  Switzerland  CHE  2019   
16498  Switzerland  CHE  2020   
16499  Switzerland  CHE  2021   
16500  Switzerland  CHE  2022   
16501  Switzerland  CHE  2023   

       Population - Sex: all - Age: all - Variant: estimates  
16428                                            4692642      
16429                                            4748088      
16430                                            4811614      
16431                                            4875655      
16432                                            4938751      
...                                                  ...      
16497                                            8577526      
16498                                            8640582      
16499                                            8707018      
16500                                            8792180      
16501                                            8870564      

[74 rows x 4 columns]

In [ ]:
# Give a friendly name to the population column
df_swiss_population = df_swiss_population.rename(
    columns={"Population - Sex: all - Age: all - Variant: estimates": "Population"}
)
df_swiss_population

Entity Code  Year  Population
16428  Switzerland  CHE  1950     4692642
16429  Switzerland  CHE  1951     4748088
16430  Switzerland  CHE  1952     4811614
16431  Switzerland  CHE  1953     4875655
16432  Switzerland  CHE  1954     4938751
...            ...  ...   ...         ...
16497  Switzerland  CHE  2019     8577526
16498  Switzerland  CHE  2020     8640582
16499  Switzerland  CHE  2021     8707018
16500  Switzerland  CHE  2022     8792180
16501  Switzerland  CHE  2023     8870564

[74 rows x 4 columns]

## Manipulate dataframe

Then I want to merge the two dataframe :


> **_Note_** : This manipulation reset index, but it possible manually (after .loc p.ex.)by using : ``df_data = df_data.reset_index()``

In [ ]:
# Join the data from the two table, only the values present in the two column !
## With function of pandas
df_swiss_data_inner_join = pd.merge(
    df_swiss_population,
    df_swiss_electricity_generation,
    on=["Year", "Entity", "Code"],
    how="inner",
)
## With methode of the df (linked to variable/object)
df_inner_join_simpler = df_swiss_population.merge(
    df_swiss_electricity_generation, on=["Year", "Entity", "Code"], how="inner"
)
df_swiss_data_inner_join.loc[0:10]

Entity Code  Year  Population  Electricity generation - TWh
0   Switzerland  CHE  1985     6470959                     56.338123
1   Switzerland  CHE  1986     6504748                     57.410492
2   Switzerland  CHE  1987     6545771                     59.733856
3   Switzerland  CHE  1988     6594145                     60.535755
4   Switzerland  CHE  1989     6647786                     54.610770
5   Switzerland  CHE  1990     6713167                     56.015427
6   Switzerland  CHE  1991     6796942                     58.061848
7   Switzerland  CHE  1992     6875049                     59.517920
8   Switzerland  CHE  1993     6938107                     61.555614
9   Switzerland  CHE  1994     6993594                     66.134240
10  Switzerland  CHE  1995     7040481                     62.862670

#### Other important part to manipulate

To merge two df, we need a key, this is a column name present on the two df, exactly the same !
- `on` = Define on wich **column** the dfs where merge (exactly same column's name need to be present on both), if parameter `on` is None this use the intersection of the two df
- `how` = Define on wich **row** the dfs where merge (find the same key)
  - `inner` = Default join, only save the key present in both df
  - `left` = Save all the key of **left**'s df, and complete with right information (when it's possible, be carefull, you will have some `NaN` value)
  - `outer` = Save all the key of both df, also have `NaN` value

If the structure between the df is **exactly** the same, you can use `concat` function, be carefull with index, not reinit :

In [ ]:
df_concat = pd.concat([df_inner_join_simpler, df_swiss_data_inner_join])
df_concat

Entity Code  Year  Population  Electricity generation - TWh
0   Switzerland  CHE  1985     6470959                     56.338123
1   Switzerland  CHE  1986     6504748                     57.410492
2   Switzerland  CHE  1987     6545771                     59.733856
3   Switzerland  CHE  1988     6594145                     60.535755
4   Switzerland  CHE  1989     6647786                     54.610770
..          ...  ...   ...         ...                           ...
34  Switzerland  CHE  2019     8577526                     70.570000
35  Switzerland  CHE  2020     8640582                     68.490000
36  Switzerland  CHE  2021     8707018                     63.100000
37  Switzerland  CHE  2022     8792180                     62.270000
38  Switzerland  CHE  2023     8870564                     70.890000

[78 rows x 5 columns]

To add information after, use the `append` method : `df1.append(df2)`

##### NaN (NaT,...) value

This value is a problem when you manipulate data.

It's possible to solve the problem with various method :
- Complete with constant value - `df=df.fillna(1)` 
  - Replace by the integer 1 if you have time series, that doesn't work, use p.ex. : `df["time"].fillna(pd.Timestamp("20221225"))`
- Remove value - `df.dropna()`
  - Remove row (parameter `axis = 0`) or column (parameter `axis = 1`) with `NaN`, by default `axis = o`
- Interpolate value - `df=df.interpolate()`
  - Fill with midpoint between the two cells

## Visualisation of the data

Now I would like to visualize the evolution of the electricity generation per capita over the time :

In [ ]:
# The basic ways to do that

# Before need to create the empty column
nb_line = df_swiss_data_inner_join.shape[0]
df_swiss_data_inner_join["Production per capita - kWh"] = np.zeros(nb_line)
# Range because int is not iterable (create a sequence of number)
for i in range(df_swiss_data_inner_join.shape[0]):
    df_swiss_data_inner_join.loc[i, "Production per capita - kWh"] = (
        df_swiss_data_inner_join.loc[i, "Electricity generation - TWh"]
        / df_swiss_data_inner_join.loc[i, "Population"]
        * 1e9
    )

The second method *__and simply__* method to do that

In [ ]:
df_swiss_data_inner_join["Production per capita 2e method - kWh"] = (
    df_swiss_data_inner_join["Electricity generation - TWh"]
    / df_swiss_data_inner_join["Population"]
    * 1e9
)

#### Another ways to do that

The power of apply plus lambda function is his simplicity, we can apply a function (lambda) to multiple row in one line of code. (Small comparison of using or not [lambda](https://www.geeksforgeeks.org/python-lambda-anonymous-functions-filter-map-reduce/#:~:text=With%20lambda%20function,Without%20lambda%20function) function)



In [ ]:
df_swiss_data_inner_join["Production per capita 3e method - kWh"] = (
    df_swiss_data_inner_join.apply(
        lambda row: row["Electricity generation - TWh"] / row["Population"] * 1e9,
        axis=1,
    )
)

It also possible to add a condition with an if function.
I would like to know if the production per capita of this year is upper than the global average.

In [ ]:
mean_production_per_capita = df_swiss_data_inner_join[
    "Production per capita - kWh"
].mean()
df_swiss_data_inner_join["Per Capita Up than mean"] = df_swiss_data_inner_join.apply(
    lambda row: (
        "Yes"
        if row["Production per capita - kWh"] > mean_production_per_capita
        else "No"
    ),
    axis=1,
)

#### Compare the three methods

If we only multiply column, the second method is the simplest.

In [ ]:
df_swiss_data_inner_join[
    [
        "Year",
        "Production per capita - kWh",
        "Production per capita 2e method - kWh",
        "Production per capita 3e method - kWh",
    ]
].loc[0:4]

Year  Production per capita - kWh  Production per capita 2e method - kWh  \
0  1985                  8706.301956                            8706.301956   
1  1986                  8825.936378                            8825.936378   
2  1987                  9125.564582                            9125.564582   
3  1988                  9180.228066                            9180.228066   
4  1989                  8214.880864                            8214.880864   

   Production per capita 3e method - kWh  
0                            8706.301956  
1                            8825.936378  
2                            9125.564582  
3                            9180.228066  
4                            8214.880864

#### Clean dataframe


Like we can see, the dataframe can have a lots informations inside, it's possible to remove certain column, or just print the part you want.

In [ ]:
# One way to remove unwanted column
df_swiss_data_clean = df_swiss_data_inner_join.drop(
    columns=[
        "Entity",
        "Code",
        "Production per capita 2e method - kWh",
        "Production per capita 3e method - kWh",
    ]
)

### Plot information

Now I would like to visualize the Population and the production per capita over time

In [ ]:
# Create a subplot to add a secondary Y axis
subfig = make_subplots(specs=[[{"secondary_y": True}]])
# Create the line plot
# fig=px.line(df_swiss_data_clean, x="Year",y=["Population","Production per capita - kWh"], title="Production per capita and population evolution in Switzerland", labels={"Population":"Population","Year":"Year"})
fig = px.line(
    df_swiss_data_clean,
    x="Year",
    y="Production per capita - kWh",
    title="Production per capita and population evolution in Switzerland",
    labels={"Population": "Population", "Year": "Year"},
)
fig2 = px.line(
    df_swiss_data_clean,
    x="Year",
    y="Population",
    title="Production per capita and population evolution in Switzerland",
    labels={"Population": "Population", "Year": "Year"},
)
fig2.update_traces(yaxis="y2")
subfig.add_traces(fig.data + fig2.data)
# To format figure
subfig.update_layout(margin=dict(l=60, r=60, t=60, b=60), width=800, height=500)

subfig.layout.xaxis.title = "Time"
subfig.layout.yaxis.title = "Production per capita - kWh"
subfig.layout.yaxis2.title = "Population"
# Show plot
subfig.for_each_trace(
    lambda t: t.update(line=dict(color=t.marker.color))
)  # Change color of each line on the plot
subfig.show()

#### Chat GPT solution

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

# Assuming your dataframe is named df_swiss_data_inner_join
fig = px.line(
    df_swiss_data_inner_join,
    x="Year",
    y="Population",
    title="Population and Production per Capita Over Time",
)

# Add the secondary y-axis
fig.add_trace(
    go.Scatter(
        x=df_swiss_data_inner_join["Year"],
        y=df_swiss_data_inner_join["Production per capita - kWh"],
        mode="lines",
        name="Production per capita - kWh",
        yaxis="y2",
    )
)

# Update layout to add a second y-axis
fig.update_layout(
    yaxis2=dict(title="Production per capita - kWh", overlaying="y", side="right"),
    yaxis=dict(title="Population"),
    xaxis=dict(title="Year"),
    legend=dict(x=0.1, y=0.9),
    margin=dict(l=60, r=60, t=60, b=60),
    width=800,
    height=500,
)

# Display the plot
fig.show()

### Dictionnary of dataframe
Pandapower make dictionnary of dataframe, here an exemple of that:

In [ ]:
df1 = pd.DataFrame({"Name": ["Shahroz", "Samad", "Usama"], "Age": [22, 35, 58]})

df2 = pd.DataFrame(
    {"Class": ["Chemistry", "Physics", "Biology"], "Students": [30, 35, 40]}
)

# list of data frames
dataframes = [df1, df2]

# dictionary to save data frames
frames = {}

for key, value in enumerate(dataframes):
    frames[key] = value  # assigning data frame from list to key in dictionary
    print("key: ", key)
    print(frames[key], "\n")

# access to one data frame by key
print("Accessing the dataframe against key 0 \n", end="")
print(frames[0])

# access to only column of specific data frame through dictionary
print("\nAccessing the first column of dataframe against key 1\n", end="")
print(frames[1]["Class"])

key:  0
      Name  Age
0  Shahroz   22
1    Samad   35
2    Usama   58 

key:  1
       Class  Students
0  Chemistry        30
1    Physics        35
2    Biology        40 

Accessing the dataframe against key 0 
      Name  Age
0  Shahroz   22
1    Samad   35
2    Usama   58

Accessing the first column of dataframe against key 1
0    Chemistry
1      Physics
2      Biology
Name: Class, dtype: object


# Pandapower

In [1]:
import pandapower as pp

Tuto on _Exercice Power flow 1 : Problème 1_

We use the librarie pandapower : [doc_pandapower](https://pandapower.readthedocs.io/en/v2.9.0/about.html)

![Problem base](plot/Ex_PF1_Pb1_Info_p.png)

Initialize the network by creating an empty network.

In [2]:
# Create an empty network
net_ExPF1_Pb1 = pp.create_empty_network(name="ExPF1_Pb1", f_hz=50, sn_mva=100)



Create all the bus

In [3]:
# create buses
b1 = pp.create_bus(net_ExPF1_Pb1, vn_kv=400.0, name="Bus 1")
b2 = pp.create_bus(net_ExPF1_Pb1, vn_kv=400.0, name="Bus 2")
b3 = pp.create_bus(net_ExPF1_Pb1, vn_kv=400.0, name="Bus 3")
b4 = pp.create_bus(net_ExPF1_Pb1, vn_kv=400.0, name="Bus 4")
b5 = pp.create_bus(net_ExPF1_Pb1, vn_kv=20.0, name="Bus 5")

In [4]:
net_ExPF1_Pb1.bus

name  vn_kv type  zone  in_service   geo
0  Bus 1  400.0    b  None        True  None
1  Bus 2  400.0    b  None        True  None
2  Bus 3  400.0    b  None        True  None
3  Bus 4  400.0    b  None        True  None
4  Bus 5   20.0    b  None        True  None

Create all the loads

In [5]:
# create load
load_2 = pp.create_load(net_ExPF1_Pb1, bus=b2, p_mw=100, q_mvar=20, name="Load 2")
load_3 = pp.create_load(net_ExPF1_Pb1, bus=b3, p_mw=200, q_mvar=80, name="Load 3")

Create all the generator and the slack bus

In [6]:
# create generator (external grid as generator to slack bus)
gen_1 = pp.create_ext_grid(net_ExPF1_Pb1, bus=b1, vm_pu=1.0, min_q_mvar=-100, max_q_mvar=100, name="Generator 1")
gen_2 = pp.create_gen(net_ExPF1_Pb1, bus=b2, vm_pu=1.05, p_mw=150, min_q_mvar=-200, max_q_mvar=200, name="Generator 2")
gen_5 = pp.create_gen(net_ExPF1_Pb1, bus=b5, vm_pu=1.0, p_mw=100, min_q_mvar=-100, max_q_mvar=100, name="Generator 5")

In [7]:
net_ExPF1_Pb1.gen

name  bus   p_mw  vm_pu  sn_mva  min_q_mvar  max_q_mvar  scaling  \
0  Generator 2    1  150.0   1.05     NaN      -200.0       200.0      1.0   
1  Generator 5    4  100.0   1.00     NaN      -100.0       100.0      1.0   

   slack  controllable  id_q_capability_characteristic  \
0  False          True                            <NA>   
1  False          True                            <NA>   

   reactive_capability_curve curve_style  in_service  slack_weight  type  
0                      False         NaN        True           0.0  None  
1                      False         NaN        True           0.0  None

Create custom transformer, pure inductor.

In [8]:
# create transformer
trafo = pp.create_transformer_from_parameters(
    net_ExPF1_Pb1,
    hv_bus=b4,
    lv_bus=b5,
    sn_mva=200,
    vn_hv_kv=400,
    vn_lv_kv=20,
    vk_percent=10,
    vkr_percent=0,
    pfe_kw=0,
    i0_percent=0,
    name="Trafo 1",
)

In [9]:
net_ExPF1_Pb1.trafo

name std_type  hv_bus  lv_bus  sn_mva  vn_hv_kv  vn_lv_kv  vk_percent  \
0  Trafo 1     None       3       4   200.0     400.0      20.0        10.0   

   vkr_percent  pfe_kw  ...  tap_step_percent  tap_step_degree tap_pos  \
0          0.0     0.0  ...               NaN              NaN     NaN   

   tap_changer_type  id_characteristic_table  tap_dependency_table  parallel  \
0               NaN                     <NA>                 False         1   

    df  in_service   oltc  
0  1.0        True  False  

[1 rows x 26 columns]

Calcul line parameter in correct units, transform from pu.

Define the base

In [15]:
S_base = 100e6
U_base = 400e3
Z_base = U_base**2 / S_base
Ligne_value = {
    "R_pu": [0.02, 0.02, 0.02, 0.04, 0.04],
    "X_pu": [0.2, 0.4, 0.4, 0.4, 0.4],
    "B_pu": [0.8, 0.8, 0.4, 0.4, 0.4],
    "Un": [400, 400, 400, 400, 400],
}
#Dictionnary value ligne
# R_pu [0.02, 0.02, 0.02, 0.04, 0.04] 
# X_pu [0.2, 0.4, 0.4, 0.4, 0.4]
# B_pu [0.8, 0.8, 0.4, 0.4, 0.4]
# Un [400, 400, 400, 400, 400]

import pandas as pd

# Create dataframe with index ["A", "B", "C", "D", "E"]
DF_Ligne = pd.DataFrame(Ligne_value, index=["A", "B", "C", "D", "E"])
DF_Ligne

R_pu  X_pu  B_pu   Un
A  0.02   0.2   0.8  400
B  0.02   0.4   0.8  400
C  0.02   0.4   0.4  400
D  0.04   0.4   0.4  400
E  0.04   0.4   0.4  400

Calcul the parameters

In [17]:
import numpy as np

rl_ohm_per_km = DF_Ligne.R_pu * Z_base
xl_ohm_per_km = DF_Ligne.X_pu * Z_base
cl_nF_per_km = DF_Ligne.B_pu / (2 * np.pi * 50 * Z_base) * 1e9
print("Line resistance :\n", rl_ohm_per_km)
print("Line impedance :\n", xl_ohm_per_km)
print("Line capacitance :\n", cl_nF_per_km)


Line resistance :
 A    32.0
B    32.0
C    32.0
D    64.0
E    64.0
Name: R_pu, dtype: float64
Line impedance :
 A    320.0
B    640.0
C    640.0
D    640.0
E    640.0
Name: X_pu, dtype: float64
Line capacitance :
 A    1591.549431
B    1591.549431
C     795.774715
D     795.774715
E     795.774715
Name: B_pu, dtype: float64


Create the lines with parameters

In [ ]:
# create line
line_a = pp.create_line_from_parameters(
    net_ExPF1_Pb1,
    from_bus=b1,
    to_bus=b2,
    length_km=1,
    r_ohm_per_km=rl_ohm_per_km.A,
    x_ohm_per_km=xl_ohm_per_km.A,
    c_nf_per_km=cl_nF_per_km.A,
    max_i_ka=1,
    name="Line A",
)

line_b = pp.create_line_from_parameters(
    net_ExPF1_Pb1,
    from_bus=b2,
    to_bus=b3,
    length_km=1,
    r_ohm_per_km=rl_ohm_per_km.B,
    x_ohm_per_km=xl_ohm_per_km.B,
    c_nf_per_km=cl_nF_per_km.B,
    max_i_ka=1,
    name="Line B",
)

line_c = pp.create_line_from_parameters(
    net_ExPF1_Pb1,
    from_bus=b3,
    to_bus=b4,
    length_km=1,
    r_ohm_per_km=rl_ohm_per_km.D,
    x_ohm_per_km=xl_ohm_per_km.D,
    c_nf_per_km=cl_nF_per_km.D,
    max_i_ka=1,
    name="Line D",
)

line_d
line_e

NameError: name 'line_b' is not defined

Check line

Check trafo

By default, we run a powerflow with NR :
- `nr` Newton-Raphson (pypower implementation with numba accelerations)
- `gs` gauss-seidel (pypower implementation)
- `fdbx` fast-decoupled (pypower implementation)

In [ ]:
# Run
pp.runpp(net_ExPF1_Pb1)
# Check the result
net_ExPF1_Pb1

Check all the result

In [ ]:
# res_bus

In [ ]:
# res_line

In [ ]:
# res_gen

In [ ]:
# res_ext_grid

To show the admitance matrix :

In [ ]:
# Need to be checked !
pd.DataFrame(net_ExPF1_Pb1._ppc["internal"]["Ybus"].toarray()).round(1)

## Same exercise with the **panda**power_heig_ui librairie

This package is based on the pandaPower library. It has been developed to help students using simple functions in order to create simple power system models.
- **panda**power_heig_ui's [documentation](https://heig-vd-ie.github.io/pandapower-heig-ui/).

In [ ]:
import pp_heig_simulation as pp_sim
import pp_heig_plot as pp_plot

At the first, we complete the excel file : *net_ex_pf_1_pb_1.xlsx*
Then we load data in **panda**power format :

In [ ]:
file_path = #excel file path
net_ExPF1_Pb1_heig = #load the network from the excel file

Check net well load :

In [ ]:
# check network

In excel, we can't create an external grid as a generator, so let's modify it manualy :

In [ ]:
# Add the min and max reactive power to external grid

In [ ]:
# Check if added

Same for generator, in excel, we only create static generator (PQ), so we need to create generator (PV)

In [ ]:
# Index gen same ways as before, don't need output
# Gen 2

# Gen 5

Check if that works :

In [ ]:
# Check if generator is aded

In [ ]:
# Check gen value

With this package, we can plot the grid :

In [ ]:
# Plot powernetwork

And simulate the powerflow

In [ ]:
# Run powerflow

Check the result between the two methods :

In [ ]:
# The two net -> net_ExPF1_Pb1_heig and net_ExPF1_Pb1
# res_line

# res_trafo

# res_ext_grid

# res_load

# res_gen

In [ ]:
print("Line result :\n", Result)
print("Bus result :\n", Result)
print("Trafo result :\n", Result)
print("Ext grid result :\n", Result)
print("Load result :\n", Result)
print("Gen result :\n", Result)

In [ ]:
# Plot plot_powerflow_result

# Show res_bus

# Annexe

### Tuto for _Compute admitance matrix_ part

In [ ]:
# Create dictionnary with values
data = {"Resistance": range(10, 101, 10), "line": range(0, 10, 1)}

# Create dataframe with the dict
resistance_DF = pd.DataFrame(data)
print(resistance_DF)
tension = 5

# Randomize order of the row
resistance_DF_rand = resistance_DF.sample(frac=1)
print(resistance_DF_rand)
nb_line = resistance_DF.shape[0]

current = np.zeros(nb_line)
for i in range(nb_line):
    line_number = resistance_DF_rand.at[i, "line"]
    current[line_number] = tension / resistance_DF_rand.at[line_number, "Resistance"]
current_DataFrame = pd.DataFrame({"Current": current})
print(current_DataFrame)